version: "2.1"
services:
  dbapp:
    image: mysql:5.6.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: madbuser
      MYSQL_PASSWORD: madbpass
      MYSQL_DATABASE: madb
    volumes:
      - ./docker/data/mysql_app:/var/lib/mysql
  apachephp:
    build:
      context: ./docker/dockerfiles/apachephp
      args:
        uid: "${CURRENT_UID:-1001}"
        gid: "${CURRENT_GID:-1001}"
    volumes:
      - ./:/var/www/html
    links:
      - dbapp
  cli:
    build:
      context: ./docker/dockerfiles/cli
      args:
        uid: "${CURRENT_UID:-1001}"
        gid: "${CURRENT_GID:-1001}"
    user: localUser
    volumes:
      - ./:/var/www/html
      - ./docker/data/composer:/home/localUser/.composer
    working_dir: /var/www/html
    links:
      - dbapp
    command: "false"
  cypress:
    build:
      context: ./docker/dockerfiles/cypress
    depends_on:
      - apachephp
    links:
      - apachephp
    volumes:
      - ./:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /e2e
    command: "true"
    ipc: host
    environment:
      - CYPRESS_baseUrl=http://apachephp:80/frontend.php
