# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
  mailer:
    class: sfMailer
    param:
      logging: %SF_LOGGING_ENABLED%
      charset: %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SendmailTransport

# You can provide smtp transport with following lines:
#  mailer:
#    class: sfMailer
#    param:
#      logging: %SF_LOGGING_ENABLED%
#      charset: %SF_CHARSET%
#      delivery_strategy: realtime
#      transport:
#        class: Swift_SmtpTransport
#        param:
#          host: smtp.gmail.com
#          port: 465
#          encryption: ssl
#          username: your_gmail_username_goes_here
#          password: your_gmail_password_goes_here


test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true
      
  i18n:
    class: sfI18N
    param:
      source:               gettext
      debug:                false
      untranslated_prefix:  "[T]"
      untranslated_suffix:  "[/T]"
      cache:
        class: sfFileCache
        param:
          automatic_cleaning_factor: 0
          cache_dir:                 %SF_I18N_CACHE_DIR%
          lifetime:                  31556926
          prefix:                    %SF_APP_DIR%/i18n

  request:
    param:
      #force symfony to not find $_SERVER['PATH_INFO'] and thus rebuild the pathinfo using $_SERVER['REQUEST_URI']
      #see sfWebRequest.class.php, method getPathInfo()
      #benefit : apache urldecodes some encoded characters in PATH_INFO, such as %2B, whereas REQUEST_URI is unaltered,
      #without this change, param value 'TiMidity%2B%2B' is translated into 'TiMidity++' by apache, then urldecoded by 
      #symfony, which gives finally 'TiMidity  ' :/
      path_info_array:        SERVER
      path_info_key:          xxSymfonyPleaseIDontWantYouToUsePathInfoxx   

