# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         mageia-app-db
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - main.css
    - selectToCheckboxes.css
    - filtering.css
    - ../fancybox/jquery.fancybox-1.3.4.css

  javascripts:
    - vendor/jquery/jquery-1.5.1.min.js
    - vendor/jquery/jquery.base64.min.js

    - vendor/jquery/jquery.ui.core.min.js
    - vendor/jquery/jquery.ui.core.min.js
    - vendor/jquery/jquery.ui.position.min.js
    - vendor/jquery/jquery.ui.widget.min.js
    - vendor/jquery/jquery.ui.mouse.min.js
    - vendor/jquery/jquery.ui.draggable.min.js
    - vendor/jquery/jquery.ui.resizable.min.js
    - vendor/jquery/jquery.ui.dialog.min.js

    - ../fancybox/jquery.easing-1.3.pack.js
    - ../fancybox/jquery.fancybox-1.3.4.js
    - ../fancybox/jquery.fancybox-1.3.4.pack.js
    - ../fancybox/jquery.mousewheel-3.0.4.pack.js

    - filtering.js
    - jquery.selectToCheckboxes.js
    - searchform.js

  has_layout:     true
  
  layout:         layout

  components:
    filtering: [ default, filtering ]
    searching: [ ]

