# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html
  toto: titi

  metas:
    title:         mageia-app-db
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - main.css
    - selectToCheckboxes.css
    - filtering.css

  javascripts:
    - jquery-1.4.4.js
    - jquery.base64.min.js
    - jquery.selectToCheckboxes.js
    - filtering.js

  has_layout:     true
  
  layout:         layout

  components:
    filtering: [ default, filtering ]
    searching: [ ]

