showSuccess:
  stylesheets:
    - package.css
  javascripts:
    - jquery.flyout-1.2.min.js
    - package.js
listSuccess:
  javascripts:
listSuccess:
  components:
    searching: [ default, searching ]
comparisonSuccess:
  components:
    searching: [ default, searching ]
    