<?php



/**
 * Skeleton subclass for performing query and update operations on the 'rpm' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.2 on:
 *
 * Sat Sep 17 11:45:49 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class RpmQuery extends BaseRpmQuery {

} // RpmQuery
