all:
  version: 0.2
  homepage:
    groups_line: 5
    rpm_limit: 6
  sf_guard_plugin:
    profile_class: User
    profile_field_name: sf_guard_user_id
    signin_form: madbFormSignin
  user:
    connector: default
