propel:
  package:
    id:                                                                ~
    name:                                                              { type: varchar(900), required: true }
    md5_name:                                                          { type: char, size:32, required: true }
    is_application:                                                    { type: boolean, required: true }
    is_source:                                                         { type: boolean, required: true }
    summary:                                                           { type: varchar(255) }
    description:                                                       longvarchar
    _indexes:
      name:                                                            [ name ]
    _uniques:
      unique_md5_name_is_source:                                       [ md5_name, is_source ]
  rpm:
    id:                                                                ~
    package_id:                                                        { type: integer, required: true, foreignTable: package, foreignReference: id }
    distrelease_id:                                                    { type: integer, required: true, foreignTable: distrelease, foreignReference: id }
    media_id:                                                          { type: integer, required: true, foreignTable: media, foreignReference: id }
    rpm_group_id:                                                      { type: integer, required: true, foreignTable: rpm_group, foreignReference: id }
    licence:                                                           { type: varchar(255), required: true }
    name:                                                              { type: varchar(900), required: true }
    md5_name:                                                          { type: varchar(45), required: true }
    short_name:                                                        { type: varchar(255), required: true }
    evr:                                                               { type: varchar(255), required: true }
    version:                                                           { type: varchar(255), required: true }
    release:                                                           { type: varchar(255), required: true }
    summary:                                                           { type: varchar(255), required: true }
    description:                                                       { type: longvarchar, required: true }
    url:                                                               { type: longvarchar, required: true }
    rpm_pkgid:                                                         { type: char, size:32, required: true }
    build_time:                                                        { type: timestamp, required: true }
    size:                                                              { type: integer, required: true }
    realarch:                                                          { type: varchar(45), required: true }
    arch_id:                                                           { type: integer, required: true, foreignTable: arch, foreignReference: id }
    is_source:                                                         { type: boolean, required: true }
    source_rpm_id:                                                     { type: integer, foreignTable: rpm, foreignReference: id }
    source_rpm_name:                                                   { type: varchar(900) }
    _indexes:
      fk_rpm_distrelease1:                                             [ distrelease_id ]
      fk_rpm_package1:                                                 [ package_id ]
      fk_rpm_rpm_group1:                                               [ rpm_group_id ]
      fk_rpm_media1:                                                   [ media_id ]
      index_name:                                                      [ name ]
      fk_rpm_arch1:                                                    [ arch_id ]
      fk_rpm_rpm1:                                                     [ source_rpm_id ]
      index_short_name:                                                [ short_name ]
      index_multi1:                                                    [ distrelease_id, media_id, arch_id, is_source ]
      index_rpm_pkgid:                                                 [ rpm_pkgid ]
      index_source_rpm_name:                                           [ source_rpm_name ]
    _uniques:
      unique_name_multi:                                               [ md5_name, distrelease_id, media_id, arch_id ]
  distrelease:
    id:                                                                ~
    name:                                                              { type: varchar(45), required: true }
    is_meta:                                                           { type: boolean, required: true, default: false }
    is_latest:                                                         { type: boolean, required: true, default: false }
    is_dev_version:                                                    { type: boolean, required: true, default: false }
    _uniques:
      unique_name:                                                     [ name ]
  user:
    id:                                                                ~
    name:                                                              { type: longvarchar, required: true }
    login:                                                             { type: varchar(255), required: true }
    _indexes:
      unique_login:                                                    [ login ]
  user_comments_package:
    id:                                                                ~
    package_id:                                                        { type: integer, required: true, foreignTable: package, foreignReference: id }
    user_id:                                                           { type: integer, required: true, foreignTable: user, foreignReference: id }
    comment:                                                           { type: longvarchar, required: true }
    created_at:                                                        ~
    _indexes:
      fk_user_comment_application_application1:                        [ package_id ]
      fk_user_comment_application_user1:                               [ user_id ]
  rpm_group:
    id:                                                                ~
    name:                                                              { type: varchar(255), required: true }
    _uniques:
      unique_name:                                                     [ name ]
  language:
    id:                                                                ~
    name:                                                              { type: varchar(255), required: true }
  package_description:
    id:                                                                ~
    version_from:                                                      { type: varchar(45) }
    package_id:                                                        { type: integer, required: true, foreignTable: package, foreignReference: id }
    language_id:                                                       { type: integer, required: true, foreignTable: language, foreignReference: id }
    _indexes:
      fk_package_description_package1:                                 [ package_id ]
      fk_package_description_language1:                                [ language_id ]
  package_screenshots:
    id:                                                                ~
    path_to_screenshot:                                                { type: varchar(1024), required: true }
    version_from:                                                      { type: varchar(45) }
    package_id:                                                        { type: integer, required: true, foreignTable: package, foreignReference: id }
    _indexes:
      fk_package_screenshots_package1:                                 [ package_id ]
  package_links:
    id:                                                                ~
    URL:                                                               { type: longvarchar, required: true }
    language_id:                                                       { type: integer, required: true, foreignTable: language, foreignReference: id }
    package_id:                                                        { type: integer, required: true, foreignTable: package, foreignReference: id }
    _indexes:
      fk_package_links_language1:                                      [ language_id ]
      fk_package_links_package1:                                       [ package_id ]
  new_version_request:
    id:                                                                ~
    user_id:                                                           { type: integer, required: true, foreignTable: user, foreignReference: id }
    package_id:                                                        { type: integer, required: true, foreignTable: package, foreignReference: id }
    distrelease_id:                                                    { type: integer, required: true, primaryKey: true, foreignTable: distrelease, foreignReference: id }
    version_needed:                                                    { type: varchar(45), required: true }
    status:                                                            { type: varchar(45), required: true }
    _indexes:
      fk_new_version_request_user1:                                    [ user_id ]
      fk_new_version_request_package1:                                 [ package_id ]
      fk_new_version_request_mga_release1:                             [ distrelease_id ]
  software_request:
    id:                                                                ~
    name:                                                              { type: varchar(255), required: true }
    url:                                                               { type: varchar(2048), required: true }
    text:                                                              { type: longvarchar, required: true }
    user_id:                                                           { type: integer, required: true, foreignTable: user, foreignReference: id }
    backport_to:                                                       longvarchar
    status:                                                            { type: varchar(45), required: true }
    _indexes:
      fk_software_request_user1:                                       [ user_id ]
  user_has_software_request:
    user_id:                                                           { type: integer, required: true, primaryKey: true, foreignTable: user, foreignReference: id }
    software_request_id:                                               { type: integer, required: true, primaryKey: true, foreignTable: software_request, foreignReference: id }
    _indexes:
      fk_user_has_software_request_user1:                              [ user_id ]
      fk_user_has_software_request_software_request1:                  [ software_request_id ]
  user_comments_software_request:
    id:                                                                ~
    user_id:                                                           { type: integer, required: true, foreignTable: user, foreignReference: id }
    software_request_id:                                               { type: integer, required: true, foreignTable: software_request, foreignReference: id }
    comment:                                                           { type: longvarchar, required: true }
    created_at:                                                        ~
    _indexes:
      fk_user_comments_software_request_user1:                         [ user_id ]
      fk_user_comments_software_request_software_request1:             [ software_request_id ]
  user_comments_new_version_request:
    id:                                                                ~
    user_id:                                                           { type: integer, required: true, foreignTable: user, foreignReference: id }
    new_version_request_id:                                            { type: integer, required: true, foreignTable: new_version_request, foreignReference: id }
    comment:                                                           { type: longvarchar, required: true }
    created_at:                                                        ~
    _indexes:
      fk_user_comments_new_version_request_user1:                      [ user_id ]
      fk_user_comments_new_version_request_new_version_request1:       [ new_version_request_id ]
  user_has_new_version_request:
    user_id:                                                           { type: integer, required: true, primaryKey: true, foreignTable: user, foreignReference: id }
    new_version_request_id:                                            { type: integer, required: true, primaryKey: true, foreignTable: new_version_request, foreignReference: id }
    _indexes:
      fk_user_has_new_version_request_user1:                           [ user_id ]
      fk_user_has_new_version_request_new_version_request1:            [ new_version_request_id ]
  arch:
    id:                                                                ~
    name:                                                              { type: varchar(45), required: true }
    _uniques:
      unique_name:                                                     [ name ]
  media:
    id:                                                                ~
    name:                                                              { type: varchar(45), required: true }
    vendor:                                                            { type: varchar(255), required: true }
    is_updates:                                                        { type: boolean, required: true }
    is_backports:                                                      { type: boolean, required: true }
    is_testing:                                                        { type: boolean, required: true }
    is_third_party:                                                    { type: boolean, required: true, default: false }
    _uniques:
      unique_name:                                                     [ name, vendor ]
  notification:
    id:                                                                ~
    user_id:                                                           { type: integer, required: true, foreignTable: user, foreignReference: id }
    update:                                                            { type: boolean, required: true, default: false }
    new_version:                                                       { type: boolean, required: true, default: false }
    update_candidate:                                                  { type: boolean, required: true, default: false }
    new_version_candidate:                                             { type: boolean, required: true, default: false }
    comments:                                                          { type: boolean, required: true, default: false }
    mail_notification:                                                 { type: boolean, required: true, default: false }
    mail_prefix:                                                       { type: varchar(45) }
    rss_feed_id:                                                       { type: integer, foreignTable: rss_feed, foreignReference: id }
    _indexes:
      fk_notification_user1:                                           [ user_id ]
      fk_notification_rss_feed1:                                       [ rss_feed_id ]
  notification_element:
    id:                                                                ~
    notification_id:                                                   { type: integer, required: true, foreignTable: notification, foreignReference: id }
    package_id:                                                        { type: integer, foreignTable: package, foreignReference: id }
    rpm_group_id:                                                      { type: integer, foreignTable: rpm_group, foreignReference: id }
    distrelease_id:                                                    { type: integer, foreignTable: distrelease, foreignReference: id }
    arch_id:                                                           { type: integer, foreignTable: arch, foreignReference: id }
    media_id:                                                          { type: integer, foreignTable: media, foreignReference: id }
    _indexes:
      fk_notification_element_notification1:                           [ notification_id ]
      fk_notification_element_package1:                                [ package_id ]
      fk_notification_element_rpm_group1:                              [ rpm_group_id ]
      fk_notification_element_distrelease1:                            [ distrelease_id ]
      fk_notification_element_arch1:                                   [ arch_id ]
      fk_notification_element_media1:                                  [ media_id ]
    _uniques:
      dummy_pk:                                                        [ notification_id, package_id, rpm_group_id, distrelease_id, arch_id, media_id ]
  rss_feed:
    id:                                                                ~
    name:                                                              { type: varchar(45) }
    hash:                                                              { type: varchar(45), required: true }
    user_id:                                                           { type: integer, required: true, foreignTable: user, foreignReference: id }
    _indexes:
      fk_rss_feed_user1:                                               [ user_id ]
    _uniques:
      hash_UNIQUE:                                                     [ hash ]
  version:
    id:                                                                ~
    version:                                                           { type: varchar(10) }
