all:
  .actions:
    login_module: sfGuardAuth
    login_action: signin

    secure_module: sfGuardAuth
    secure_action: secure

  .settings:
    enabled_modules:
      - sfGuardAuth
    standard_helpers:
      - Partial
      - Cache
      - crossAppLink

prod:
 .settings:
    error_reporting:  <?php echo (E_ALL | E_STRICT)."\n" ?>

dev:
  .settings:
    error_reporting:  <?php echo (E_ALL | E_STRICT)."\n" ?>
