name: CI

on: [push, pull_request]

jobs:
  functional:
    name: "Functional tests"
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Tests - Functional
        run: make test-functional
